cache: bundler
before_install:
  - gem install bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - jruby-9.1.8.0
  - jruby-head
  - ruby-head
notifications:
  email:
    on_success: change
    on_failure: always
